### ISSUE TITLE
Remove raw data from exception to prevent information disclosure in stack traces.

### ISSUE THREAD

**Issue by iramiller** [komputing/KBase58#1]
This line in the base58 class throws an exception with the raw data being decoded... this is a bad choice because...
https://github.com/komputing/KBase58/blob/121e7f09328ea12099ff6be626d32341f6b8ea23/kbase58/src/main/kotlin/org/komputing/kbase58/Base58.kt#L160

This line in the KEthereum library uses the above function to decode keys ... meaning that the private key can be dropped in stack traces, which end up in log files... Very bad.
https://github.com/komputing/KEthereum/blob/1e7d129f5c3d2f7d71123f760f396827ef980170/bip32/src/main/kotlin/org/kethereum/bip32/Converter.kt#L49

**Comment by ligi** [comment]
It would not end up in log files as I see but throw an exception. What alternative approach do you propose?

**Comment by iramiller** [comment]
I would recommend removing the `$this` from the exception.  The raw input is not needed for context in the error message.  The source caller will have this information.  What they will not have is the context of "checksum mismatch" or perhaps the checksum itself.

This change will allow a consuming library that throws this error in a stack trace to not leak sensitive information.  The KEthereum library above is a good example of a downstream library that is vulnerable to this leak.

**Comment by ligi** [comment]
yes this makes sense - will do the change - thanks for reporting!
